# Changes here will be overwritten by Copier
_commit: v2.3.0
_src_path: gh:2e0byo/MassTemplate
alleluia: alleluia
asperges: vidi-aquam
creator_name: John Morris
creed: 1
creed_path: ../Ordinaries/credo
creedp: true
feast_name: Dominica V Post Pascha
gloria: true
gradual: true
img_file: ../img/logo.eps
marian: true
mass_setting: 1
mass_type: Missa Cantata
masses_path: ../Ordinaries/masses
preface: standard
repo_url: https://github.com/St-Josephs-Gateshead/Masses
rite: roman
version: v1.0.1
