# Changes here will be overwritten by Copier
_commit: v2.3.0
_src_path: gh:2e0byo/MassTemplate.git
alleluia: alleluia
asperges: ''
creator_name: John Morris
creed: 1
creed_path: ../Ordinaries/credo
creedp: true
feast_name: In Epiphania Domini
gloria: true
gradual: true
img_file: ../img/logo.pdf
marian: true
mass_setting: 2
mass_type: Missa Cantata
masses_path: ../Ordinaries/masses
preface: standard
repo_url: https://github.com/St-Josephs-Gateshead/Masses
rite: roman
version: v1.0.0
