# Changes here will be overwritten by Copier
_commit: v2.4.6
_src_path: gh:St-Josephs-Gateshead/MassTemplate.git
alleluia: tract
asperges: asperges
common_tones_path: ../ToniCommunes
creator_name: John Morris
creed: 1
creed_path: ../Ordinaries/credo
creedp: true
feast_name: Dominica II in Quadragesima
gloria: false
gradual: true
img_file: ../img/logo.pdf
marian: true
marian_path: ../MarianAntiphons
marian_type: ave-regina-caelorum
mass_setting: 17
mass_type: Missa Cantata
masses_path: ../Ordinaries/masses
preface: simple
repo_url: https://github.com/St-Josephs-Gateshead/Masses
rite: roman
sequentia: false
version: v1.0.1
