# Changes here will be overwritten by Copier
_commit: v2.4.8
_src_path: gh:St-Josephs-Gateshead/MassTemplate.git
alleluia: tract
asperges: ''
common_tones_path: ../ToniCommunes
creator_name: Anne Foo
creedp: false
feast_name: Feria IV Cinerum (Ash Wednesday)
gloria: false
gradual: true
img_file: ../img/logo.pdf
marian: true
marian_path: ../MarianAntiphons
marian_type: ave-regina-caelorum
mass_setting: 17
mass_type: Missa Cantata
masses_path: ../Ordinaries/masses
preface: standard
repo_url: https://github.com/St-Josephs-Gateshead/Masses
rite: roman
sequentia: false
version: v1.0.0
