on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          pip install httpx
          python scripts/configure.py
          echo "Makefile is:"
          cat makefile
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add git
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            apk add make
            make -j $(nproc)
      - run: |
          python scripts/package.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            pdfs/*.pdf
