on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install
        run: nix develop --command true
      - name: generate makefile
        run: |-
          nix develop --command python scripts/configure.py
          echo "Makefile is:"
          cat makefile
      - name: build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          sh scripts/post-xxx-sample.txt # gitinfo2 script
          while true
          do
            free -h
            sleep 30
          done &
          ncpu
          nix develop --command make -j 4
      - run: |
          nix develop --command python scripts/package.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            pdfs/*.pdf
