on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: generate makefile
        run: |-
          nix develop --command python scripts/configure.py
          echo "Makefile is:"
          cat makefile
      - name: build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          nix develop --command make -j
      - run: |
          nix develop --command python scripts/package.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            pdfs/*.pdf
