on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install
        run: nix develop --command true
      - name: Run CI script
        run: nix develop --command scripts/ci.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            pdfs/*.pdf
