on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: |
          pip install httpx
          python scripts/configure.py
          cat makefile
          make -j $(nproc)
          python scripts/package.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            pdfs/*.pdf
