on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          pip install httpx
          python scripts/configure.py
          echo "Makefile is:"
          cat makefile
      - name: install latex
        run: |
          sudo apt update && sudo apt install -y texlive texlive-music texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended latexmk
      - name: build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make -j
      - run: |
          python scripts/package.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            pdfs/*.pdf
