name: Generate PDFs

on:
  push:
    tags:
      - "r[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: check tags
        if: ${{github.event_name}} != 'push'
        run: |
          if [[ "$GITHUB_REF" != "refs/tags/"* ]]; then
            echo "not triggered with tag!" && exit 1
          fi
      - uses: DeterminateSystems/nix-installer-action@main
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install
        run: nix develop --command true
      - name: Run CI script
        run: |
          nix develop --command scripts/ci.sh
      - name: upload artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: pdfs/*.pdf

      - name: create release
        uses: "softprops/action-gh-release@v2"
        with:
          tag_name: ${{github.ref_name}}
          make_latest: ${{github.event_name == 'push'}}
          generate_release_notes: true
          files: |
            pdfs/*.pdf
