# Changes here will be overwritten by Copier
_commit: v2.4.7
_src_path: gh:St-Josephs-Gateshead/MassTemplate.git
alleluia: alleluia
asperges: vidi-aquam
common_tones_path: ../ToniCommunes
creator_name: Anne Foo
creed: 1
creed_path: ../Ordinaries/credo
creedp: true
feast_name: Dominica Resurrectionis
gloria: false
gradual: true
img_file: ../img/logo.pdf
marian: true
marian_path: ../MarianAntiphons
marian_type: regina-caeli
mass_setting: 1
mass_type: Missa Cantata
masses_path: ../Ordinaries/masses
preface: standard
repo_url: https://github.com/St-Josephs-Gateshead/Masses
rite: roman
sequentia: true
version: v1.0.0
